rendu_cinema2:
    resource: "@RenduCinema2Bundle/Controller/"
    type:     annotation
    prefix:   /

rendu_cinema:
    resource: "@RenduCinemaBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
